INSERT INTO ksis.option_values (option_id, value) VALUES (1, 'iOS');
INSERT INTO ksis.option_values (option_id, value) VALUES (1, 'Android 4.1');
INSERT INTO ksis.option_values (option_id, value) VALUES (1, 'Android 4.2');
INSERT INTO ksis.option_values (option_id, value) VALUES (1, 'Windows Mobile');
INSERT INTO ksis.option_values (option_id, value) VALUES (2, 'Apple');
INSERT INTO ksis.option_values (option_id, value) VALUES (2, 'Samsung');
INSERT INTO ksis.option_values (option_id, value) VALUES (2, 'HTC');
INSERT INTO ksis.option_values (option_id, value) VALUES (2, 'Google');
INSERT INTO ksis.option_values (option_id, value) VALUES (3, 'Белый');
INSERT INTO ksis.option_values (option_id, value) VALUES (3, 'Черный');
INSERT INTO ksis.option_values (option_id, value) VALUES (3, 'Синий');
INSERT INTO ksis.option_values (option_id, value) VALUES (3, 'Желтый');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '140');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '150');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '220');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '300');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '160');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '112');
INSERT INTO ksis.option_values (option_id, value) VALUES (5, '1400');
INSERT INTO ksis.option_values (option_id, value) VALUES (1, 'Andoid 4.0');
INSERT INTO ksis.option_values (option_id, value) VALUES (4, '133');